### ISSUE TITLE
Python 3.12 wheel packages for PyPi

### ISSUE THREAD

**Issue by mathoudebine** [mark9064/pyamdgpuinfo#11]
Hi, with the recent release of Python 3.12 in 2023-10-02 it would be nice to have precompiled wheels for Python 3.12 uploaded to PyPi
Still using your library as a dependency in the [turing-smart-screen-python project](https://github.com/mathoudebine/turing-smart-screen-python/) to get AMD GPU sensors on Linux and display it on smart displays.
It works like a charm!
Thanks

**Comment by mark9064** [comment]
Thanks for the heads up! Unfortunately I have to migrate to new CI as the manylinux builder I was using has been deprecated, so I can't push out a new version immediately. I'll get on this as soon as possible though

**Comment by mark9064** [comment]
Updated now :)
Sorry for the wait, especially if it blocked some release of your project

**Comment by mathoudebine** [comment]
> Updated now :) Sorry for the wait, especially if it blocked some release of your project

Many thanks! It was not blocking at all, just wanted to anticipate the Python 3.12 migration :)
