### ISSUE TITLE
Request: Build and upload python 3.9 wheel to PyPl

### ISSUE THREAD

**Issue by DeadEnded** [mark9064/pyamdgpuinfo#3]
Any chance you can build a wheel for this and have that uploaded to PyPl too?

I am toying around building a custom component for Home Assistant, but it is trying to install source and doesn't have gcc, etc. to build the wheel.  Would you be willing to build a wheel for this?  That should remove this barrier.

Thanks!
DeadEnd

**Comment by mark9064** [comment]
Ah, there are wheels for 3.5-3.8 but because I did the last CI build before 3.9 released, there currently isn't a wheel for 3.9. I'll get round to uploading a 3.9 wheel soon

**Comment by mark9064** [comment]
Should be done :smile: let me know if it works OK

**Comment by DeadEnded** [comment]
Doesn't appear to have worked... but I'm a novice, so maybe I did something wrong...
```
bash-5.0# pip3 install pyamdgpuinfo
Collecting pyamdgpuinfo
  Downloading pyamdgpuinfo-2.1.1.tar.gz (9.9 kB)
Building wheels for collected packages: pyamdgpuinfo
  Building wheel for pyamdgpuinfo (setup.py) ... error
```

**Comment by DeadEnded** [comment]
I did some digging trying to figure this out...
I was able to find this on pypi:
![image](https://user-images.githubusercontent.com/45110141/112092058-13834c00-8b6d-11eb-96bd-a936e767f085.png)

So I think I know what the problem is... the container image I believe is based on Alpine.
From what I gather, manylinux wheels are not supported on Alpine.
So - I'll keep digging to see if I can find a workaround that doesn't require installing gcc, musl-dev, and libdrm-dev (as this would need to be done on over container image update). 

Thanks!
DeadEnd

**Comment by DeadEnded** [comment]
Okay, so I was able to build a local wheel and install it... so I guess my options are to either host/store the wheel myself somewhere and setup the requirement to point to that (probably not ideal) or to ask very politely for you to build your wheels either as `-none-linux_86_64` or as `-none-any` as those appear to be tags that work based on `python -m pip debug --verbose`.

That being said, I have no working knowledge of what that would entail - but I would hazard the guess that it wouldn't be easy... From what I have read, it sounds like possibly PyPi doesn't even accept none `manylinux` wheels, is that correct?  If that is the case, I guess I'll have to further look into option A (host myself).

Thanks!
DeadEnd

**Comment by mark9064** [comment]
Yeah you'll find that you run into this problem for just about every package with compiled code on PyPi. For this reason Alpine is generally not recommended for deploying python stuff AFAIK, but if it's just a small component of your project I can see why you might want to stick with it. Anyway, you are right in that PyPi currently only accepts manylinux builds with glibc. Currently, musl support is a draft, see [PEP 656](https://www.python.org/dev/peps/pep-0656/). So unfortunately you'll have to look into self building/hosting.

Hey, at least it was a good opportunity for me to update my CI :smile:

Edit: I'd be happy to offer musl builds if/when that PEP is approved and is implemented - but for now deploying such wheels is unfortunately impossible

**Comment by DeadEnded** [comment]
Thanks!
After doing a little research I realized that too - looks like it's a possibility in the future though.
What I am working on is a custom component for Home Assistant.  It is container-based, and built from alpine... it seems like most people haven't run into this problem. I guess most of the custom components others have built can be built from source on alpine.  I'm still looking through custom components to see if anyone has run into this issue and how they got around it.

I was thinking at least temporarily I could put the wheel on github and then in `manifest.json` somehow set the requirement to the already built wheel... but I'm a novice and don't know how to do it... so still trying to figure that out.

Anyway, I can close this issue - thanks for the help!
DeadEnd

**Comment by DeadEnded** [comment]
okay... if you have a minute to ponder with me... I am finding pypi projects that are not `manylinux`... so is it possible that wheels other than `manylinux` can be published?

![image](https://user-images.githubusercontent.com/45110141/112200829-022a5600-8be6-11eb-8a39-86c2efc20245.png)

Just trying to understand - sorry if I'm being a bother.
DeadEnd

**Comment by mark9064** [comment]
If the project has C code it must be compiled against a libc implementation
If it does not (ie is pure python), then it is automatically compatible with any (version permitting) python interpreter, and is therefore a universal wheel
