### ISSUE TITLE
python 3.10 wheel

### ISSUE THREAD

**Issue by codifryed** [mark9064/pyamdgpuinfo#6]
Hi :wave:, any chance of getting a 3.10 wheel built and pushed to pypi? 
Thanks for the handy package btw.

**Comment by mark9064** [comment]
Just published v2.1.2 with 3.10 support. Let me know if it works OK :smile:

**Comment by codifryed** [comment]
Thanks! I'll check it out

**Comment by mark9064** [comment]
I'm assuming by the lack of response that it's resolved now :) thanks for pointing it out

**Comment by codifryed** [comment]
Sorry, yep 👍 confirmed working without issue in python 3.10
