### ISSUE TITLE
Python 3.11 wheel packages for PyPi

### ISSUE THREAD

**Issue by mathoudebine** [mark9064/pyamdgpuinfo#9]
Hi, with the release of Python 3.11 in late 2022 it would be nice to have precompiled wheels for Python 3.11 uploaded to PyPi
FYI we are actively using your library as a dependency in the [turing-smart-screen-python project](https://github.com/mathoudebine/turing-smart-screen-python/) to get AMD GPU sensors on Linux and display it on smart displays.
Thanks!

**Comment by mark9064** [comment]
Should be done now, let me know if it works ok!

**Comment by mathoudebine** [comment]
Thanks, works like a charm!
